### ISSUE TITLE
sign in probem

### ISSUE THREAD

**Issue by iamshubhamsaroj** [ashuvssut/women-safety-app#1]
authentication  is not working it says "network error please try again later" .

**Comment by peanub07** [comment]
Hi @iamshubhamsaroj , 

Actually I removed the firebase project from my account which provided OAuth2 service to the current app (I can enable it again)

you can setup you own firebase project and enable authentication service for your own build😄.

**Comment by ashuvssut** [comment]
Hi @iamshubhamsaroj, the basic functionality of this app works fine. If you want to contribute, to setup your local dev environment, it is recommended to create your own firebase project instance for authentication service. You need to use a physical device with GPS and SMS service to test the basic functionality.

Currently I am closing this issue. If you have any queries feel free ask!

**Comment by ashuvssut** [comment]
Hi @iamshubhamsaroj, the basic functionality of this app works fine. If you want to contribute, to setup your local dev environment, it is recommended to create your own firebase project instance for authentication service. You need to use a physical device with GPS and SMS service to test the basic functionality.

Currently I am closing this issue. If you have any queries feel free ask!

**Comment by peanub07** [comment]
Hi @iamshubhamsaroj i have re-initialized the firebase project. You should be able to signin now
